/***************************************************************************
 * Jeffrey H. Tan                                                          *
 * 2022 Spring CSC 133-04 Professor Posnett                                *
 * Project: Hornets HDF                                                    *
 * Simple 2D top-down video game.                                          *
 * Player controls a helicopter to collect water to fight the fire.        *
 * Program with codename one API,                                          *
 * cross-platform app development using Java. (PC, android, IOS)           *
 ***************************************************************************/
package org.csc133.a3;

import com.codename1.system.Lifecycle;

/**
 * This file was generated by
 * <a href="https://www.codenameone.com/">Codename One</a>
 * for the purpose of building native mobile applications using Java.
 */
public class AppMain extends Lifecycle {
    @Override
    public void runApp() {
        new Game();
    }
}
